export const columns = [
  {
    title: "Backlog",
    tasks: [
      {
        id: 1,
        title: `Add discount code to checkout page`,
        date: 1649845411000,
        type: "Feature Request",
        desc: "Add a discount code to the checkout page.",
        priority: "High",
        image: "https://randomuser.me/api/portraits/thumb/women/9.jpg",
        name: "Käthe Sikora",
      },
      {
        id: 2,
        title: `Provide documentation on integrations`,
        date: 1649759011000,
        desc: "Provide documentation on integrations",
        priority: "Medium",
        image: "https://randomuser.me/api/portraits/thumb/men/72.jpg",
        name: "Luca Bonnet",
      },
      {
        id: 3,
        title: "Design shopping cart dropdown",
        date: 1649672611000,
        type: "Design",
        desc: "Design shopping cart dropdown",
        priority: "Low",
        image: "https://randomuser.me/api/portraits/thumb/men/18.jpg",
        name: "Bastien",
      },
      {
        id: 4,
        title: `Add discount code to checkout page`,
        date: 1649586211000,
        type: "Feature Request",
        desc: "Add discount code to checkout page",
        priority: "High",
        image: "https://randomuser.me/api/portraits/thumb/men/22.jpg",
        name: "Francisco Berry",
      },
      {
        id: 5,
        title: `Test checkout flow`,
        date: 1649499811000,
        type: "QA",
        desc: "Test checkout flow",
        priority: "Low",
        image: "https://randomuser.me/api/portraits/thumb/men/22.jpg",
        name: "Francisco Berry",
      },
    ],
  },
  {
    title: "In Progress",
    tasks: [
      {
        id: 6,
        title: "Design shopping cart dropdown",
        date: 1649413411000,
        type: "Design",
        desc: "Design shopping cart dropdown",
        priority: "Low",
        image: "https://randomuser.me/api/portraits/thumb/women/9.jpg",
        name: "Käthe Sikora",
      },
      {
        id: 7,
        title: "Add discount code to checkout page",
        date: 1649327011000,
        type: "Feature Request",
        desc: "Add discount code to checkout page",
        priority: "Medium",
        image: "https://randomuser.me/api/portraits/thumb/men/72.jpg",
        name: "Luca Bonnet",
      },
      {
        id: 8,
        title: "Provide documentation on integrations",
        date: 1649240611000,
        type: "Backend",
        desc: "Provide documentation on integrations",
        priority: "High",
        image: "https://randomuser.me/api/portraits/thumb/men/22.jpg",
        name: "Francisco Berry",
      },
    ],
  },
  {
    title: "Blocked",
    tasks: [
      {
        id: 17,
        title: "Design shopping cart dropdown",
        date: 1649154211000,
        type: "Design",
        desc: "Design shopping cart dropdown",
        priority: "High",
        image: "https://randomuser.me/api/portraits/thumb/men/18.jpg",
        name: "Bastien",
      },
      {
        id: 18,
        title: "Add discount code to checkout page",
        date: 1649067811000,
        type: "Feature Request",
        desc: "Add discount code to checkout page",
        priority: "High",
        image: "https://randomuser.me/api/portraits/thumb/men/18.jpg",
        name: "Bastien",
      },
      {
        id: 19,
        title: "Provide documentation on integrations",
        date: 1648981411000,
        type: "Backend",
        desc: "Provide documentation on integrations",
        priority: "Low",
        image: "https://randomuser.me/api/portraits/thumb/men/22.jpg",
        name: "Francisco Berry",
      },
    ],
  },
  {
    title: "Review",
    tasks: [
      {
        id: 9,
        title: `Provide documentation on integrations`,
        date: 1648981411000,
        desc: "Provide documentation on integrations",
        priority: "Medium",
        image: "https://randomuser.me/api/portraits/thumb/women/0.jpg",
        name: "مرسانا حیدری",
      },
      {
        id: 10,
        title: "Design shopping cart dropdown",
        date: 1648808611000,
        type: "Design",
        desc: "Design shopping cart dropdown",
        priority: "High",
        image: "https://randomuser.me/api/portraits/thumb/men/90.jpg",
        name: "بردیا كامياران",
      },
      {
        id: 11,
        title: `Add discount code to checkout page`,
        date: 1648722211000,
        type: "Feature Request",
        desc: "Add discount code to checkout page",
        priority: "Low",
        image: "https://randomuser.me/api/portraits/thumb/men/37.jpg",
        name: "Obbe Loukili",
      },
      {
        id: 12,
        title: `Design shopping cart dropdown`,
        date: 1648722211000,
        type: "Design",
        desc: "DDesign shopping cart dropdown",
        priority: "Medium",
        image: "https://randomuser.me/api/portraits/thumb/men/40.jpg",
        name: "Anoop",
      },
      {
        id: 13,
        title: `Add discount code to checkout page`,
        date: 1648549411000,
        type: "Feature Request",
        desc: "Add discount code to checkout page",
        priority: "High",
        image: "https://randomuser.me/api/portraits/thumb/men/40.jpg",
        name: "Anoop",
      },
    ],
  },
  {
    title: "Done",
    tasks: [
      {
        id: 14,
        title: "Add discount code to checkout page",
        date: 1648463011000,
        type: "Feature Request",
        desc: "Add discount code to checkout page",
        priority: "High",
        image: "https://randomuser.me/api/portraits/thumb/men/37.jpg",
        name: "Obbe Loukili",
      },
      {
        id: 15,
        title: "Design shopping cart dropdown",
        date: 1648376611000,
        type: "Design",
        desc: "Design shopping cart dropdown",
        priority: "Low",
        image: "https://randomuser.me/api/portraits/thumb/men/90.jpg",
        name: "بردیا كامياران",
      },
      {
        id: 16,
        title: "Add discount code to checkout page",
        date: 1648290211000,
        type: "Feature Request",
        desc: "Add discount code to checkout page",
        priority: "Medium",
        image: "https://randomuser.me/api/portraits/thumb/men/40.jpg",
        name: "Anoop",
      },
    ],
  },
];
