export const columns = [
  {
    title: "Backlog",
    tasks: [
      {
        id: 1,
        title: `Add discount code to checkout page`,
        date: 1648803852000,
        type: "Feature Request",
        desc: "Discout code blah blah blah",
        priority: "High",
        image: "https://randomuser.me/api/portraits/thumb/women/9.jpg",
        name: "Käthe Sikora",
      },
      {
        id: 2,
        title: `Provide documentation on integrations`,
        date: 1641975260000,
        desc: "Discout code blah blah blah",
        priority: "Medium",
        image: "https://randomuser.me/api/portraits/thumb/men/72.jpg",
        name: "Luca Bonnet",
      },
      {
        id: 3,
        title: "Design shopping cart dropdown",
        date: 1641716060000,
        type: "Design",
        desc: "Discout code blah blah blah",
        priority: "Low",
        image: "https://randomuser.me/api/portraits/thumb/men/18.jpg",
        name: "Bastien",
      },
      {
        id: 4,
        title: `Add discount code to checkout page`,
        date: 1642148060000,
        type: "Feature Request",
        desc: "Discout code blah blah blah",
        priority: "High",
        image: "https://randomuser.me/api/portraits/thumb/men/22.jpg",
        name: "Francisco Berry",
      },
      {
        id: 5,
        title: `Test checkout flow`,
        date: 1642234460000,
        type: "QA",
        desc: "Discout code blah blah blah",
        priority: "Low",
        image: "https://randomuser.me/api/portraits/thumb/men/22.jpg",
        name: "Francisco Berry",
      },
    ],
  },
  {
    title: "In Progress",
    tasks: [
      {
        id: 6,
        title: "Design shopping cart dropdown",
        date: 1644394460000,
        type: "Design",
        desc: "Discout code blah blah blah",
        priority: "Low",
        image: "https://randomuser.me/api/portraits/thumb/women/9.jpg",
        name: "Käthe Sikora",
      },
      {
        id: 7,
        title: "Add discount code to checkout page",
        date: 1644826460000,
        type: "Feature Request",
        desc: "Discout code blah blah blah",
        priority: "Medium",
        image: "https://randomuser.me/api/portraits/thumb/men/72.jpg",
        name: "Luca Bonnet",
      },
      {
        id: 8,
        title: "Provide documentation on integrations",
        date: 1644653660000,
        type: "Backend",
        desc: "Discout code blah blah blah",
        priority: "High",
        image: "https://randomuser.me/api/portraits/thumb/men/22.jpg",
        name: "Francisco Berry",
      },
    ],
  },
  {
    title: "Blocked",
    tasks: [
      {
        id: 17,
        title: "Design shopping cart dropdown",
        date: 1644394460000,
        type: "Design",
        desc: "Discout code blah blah blah",
        priority: "High",
        image: "https://randomuser.me/api/portraits/thumb/men/18.jpg",
        name: "Bastien",
      },
      {
        id: 18,
        title: "Add discount code to checkout page",
        date: 1647245660000,
        type: "Feature Request",
        desc: "Discout code blah blah blah",
        priority: "High",
        image: "https://randomuser.me/api/portraits/thumb/men/18.jpg",
        name: "Bastien",
      },
      {
        id: 19,
        title: "Provide documentation on integrations",
        date: 1647072860000,
        type: "Backend",
        desc: "Discout code blah blah blah",
        priority: "Low",
        image: "https://randomuser.me/api/portraits/thumb/men/22.jpg",
        name: "Francisco Berry",
      },
    ],
  },
  {
    title: "Review",
    tasks: [
      {
        id: 9,
        title: `Provide documentation on integrations`,
        date: 1647850460000,
        desc: "Discout code blah blah blah",
        priority: "Medium",
        image: "https://randomuser.me/api/portraits/thumb/women/0.jpg",
        name: "مرسانا حیدری",
      },
      {
        id: 10,
        title: "Design shopping cart dropdown",
        date: 1646813660000,
        type: "Design",
        desc: "Discout code blah blah blah",
        priority: "High",
        image: "https://randomuser.me/api/portraits/thumb/men/90.jpg",
        name: "بردیا كامياران",
      },
      {
        id: 11,
        title: `Add discount code to checkout page`,
        date: 1647245660000,
        type: "Feature Request",
        desc: "Discout code blah blah blah",
        priority: "Low",
        image: "https://randomuser.me/api/portraits/thumb/men/37.jpg",
        name: "Obbe Loukili",
      },
      {
        id: 12,
        title: `Design shopping cart dropdown`,
        date: 1646813660000,
        type: "Design",
        desc: "Discout code blah blah blah",
        priority: "Medium",
        image: "https://randomuser.me/api/portraits/thumb/men/40.jpg",
        name: "Anoop",
      },
      {
        id: 13,
        title: `Add discount code to checkout page`,
        date: 1647245660000,
        type: "Feature Request",
        desc: "Discout code blah blah blah",
        priority: "High",
        image: "https://randomuser.me/api/portraits/thumb/men/40.jpg",
        name: "Anoop",
      },
    ],
  },
  {
    title: "Done",
    tasks: [
      {
        id: 14,
        title: "Add discount code to checkout page",
        date: 1644826460000,
        type: "Feature Request",
        desc: "Discout code blah blah blah",
        priority: "High",
        image: "https://randomuser.me/api/portraits/thumb/men/37.jpg",
        name: "Obbe Loukili",
      },
      {
        id: 15,
        title: "Design shopping cart dropdown",
        date: 1641716060000,
        type: "Design",
        desc: "Discout code blah blah blah",
        priority: "Low",
        image: "https://randomuser.me/api/portraits/thumb/men/90.jpg",
        name: "بردیا كامياران",
      },
      {
        id: 16,
        title: "Add discount code to checkout page",
        date: 1647245660000,
        type: "Feature Request",
        desc: "Discout code blah blah blah",
        priority: "Medium",
        image: "https://randomuser.me/api/portraits/thumb/men/40.jpg",
        name: "Anoop",
      },
    ],
  },
];
